project_id = "ovnpankwmmrmhqkxsqqq"
[functions.create-checkout-session]
enabled = true
verify_jwt = false
import_map = "./functions/create-checkout-session/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-checkout-session/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-checkout-session/*.html" ]

[functions.stripe-webhooks]
enabled = true
verify_jwt = false
import_map = "./functions/stripe-webhooks/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/stripe-webhooks/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/stripe-webhooks/*.html" ]

[functions.create-customer-portal-session]
enabled = true
verify_jwt = false
import_map = "./functions/create-checkout-session/deno.json"
entrypoint = "./functions/create-customer-portal-session/index.ts"
