// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovnpankwmmrmhqkxsqqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92bnBhbmt3bW1ybWhxa3hzcXFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDA1NjQsImV4cCI6MjA2MDU3NjU2NH0.2xkUmKILhpPR2CkzvWl7pJenRNA2gEsn1Q3P1fDsIqY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);